### PR TITLE
Migrating to OIDC

### LINKED ISSUE #186: Migrate from long-lived credentials to OIDC
Similarly to what we did [here](https://github.com/nearform/fastify-secrets-aws/pull/308).

### PR DESCRIPTION
**Pull request by alcidesqueiroz**
Closes #186

### CODE REVIEW

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
@alcidesqueiroz not sure why but after merging this PR the build on master failed, can you please take a look?

**Comment by alcidesqueiroz** [comment]
@simoneb I know what happened and I've just fixed it. I had to create a second Federated Credential. I had created one for Pull Requests already (that's why the PR build was passing), now I created one for the master branch (fixing the build on master).

**Comment by simoneb** [comment]
why do we need 2 credentials?

**Comment by alcidesqueiroz** [comment]
@simoneb Because each credential is tied to a single entity type (which might be either branch, pr, environment or tag) and subject identifier. The subject identifier will change depending on the GitHub Actions' context, e.g. if it's a PR or if it's running on a given branch. As it's not possible to set more than a single identifier per credential, I had to create two separate credentials, one for each entity type (PRs and master branch).

**Comment by simoneb** [comment]
understood, thanks, I wasn't aware of that

**Pull request merged**
